### ISSUE TITLE
Cannot browse docs locally: gitdocs serve is broken

### ISSUE THREAD

**Issue by rhymes** [forem/forem#11181]
In the https://docs.dev.to/contributing/docs/ we say `yarn gitdocs serve` is needed to browse documentation locally.
Unfortunately the command doesn't work. It fails with the following message

```shell
> yarn gitdocs serve
yarn run v1.22.5
$ /Development/forem/node_modules/.bin/gitdocs serve

      GitDocs

❯ Starting local development server
❯ [✓] Syntax loaded
❯ [✓] Static assets loaded
❯ Generated and hydrated manifest
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND UnsetENVvariable:IMGPROXY_KEY.UnsetENVvariable:IMGPROXY_SALT.UnsetENVvariable:RELEASE_FOOTPRINT.DEPRECATIONWARNING:InitializationautoloadedtheconstantsAudit,Audit::Helper,Audit::Subscribe,Images,Images::Optimizer,RateLimitChecker,ReverseMarkdown::Converters::CustomPre,andReverseMarkdown::Converters::CustomText.Beingabletodothisisdeprecated.AutoloadingduringinitializationisgoingtobeanerrorconditioninfutureversionsofRails.Reloadingdoesnotreboottheapplication,andthereforecodeexecutedduringinitializationdoesnotrunagain.So,ifyoureloadAudit,forexample,theexpectedchangeswon'tbereflectedinthatstaleModuleobject.Theseautoloadedconstantshavebeenunloaded.Please,checkthe"AutoloadingandReloadingConstants"guideforsolutions.(calledfrom<main>at/Development/forem/config/environment.rb:5)**[Honeybadger]InitializingHoneybadgerErrorTrackerforRuby.Shipit!version=4.7.2framework=railslevel=1pid=15756localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (events.js:315:20)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1495:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:17) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: `UnsetENVvariable:IMGPROXY_KEY.UnsetENVvariable:IMGPROXY_SALT.UnsetENVvariable:RELEASE_FOOTPRINT.DEPRECATIONWARNING:InitializationautoloadedtheconstantsAudit,Audit::Helper,Audit::Subscribe,Images,Images::Optimizer,RateLimitChecker,ReverseMarkdown::Converters::CustomPre,andReverseMarkdown::Converters::CustomText.Beingabletodothisisdeprecated.AutoloadingduringinitializationisgoingtobeanerrorconditioninfutureversionsofRails.Reloadingdoesnotreboottheapplication,andthereforecodeexecutedduringinitializationdoesnotrunagain.So,ifyoureloadAudit,forexample,theexpectedchangeswon'tbereflectedinthatstaleModuleobject.Theseautoloadedconstantshavebeenunloaded.Please,checkthe"AutoloadingandReloadingConstants"guideforsolutions.(calledfrom<main>at/Development/forem/config/environment.rb:5)**[Honeybadger]InitializingHoneybadgerErrorTrackerforRuby.Shipit!version=4.7.2framework=railslevel=1pid=15756localhost`
}
```

I also tried to remove `.gitdocs.js` but I get the following error afterwards:

```shell
❯ Starting local development server
❯ [✓] Syntax loaded
❯ Duplicated URL was found: /node_modules/array.prototype/
	- /Development/forem/node_modules/array.prototype.flatmap/README.md
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**

1. Run `yarn gitdocs serve` from the `docs` folder or from the root folder of the forem project

**Expected behavior**

the command to work

**Comment by sjarva** [comment]
I'd like to work on this one, please! 😊

**Comment by rhymes** [comment]
@sjarva thanks for volunteering! I've assigned it to you
