### ISSUE TITLE
Elasticsearch error while setting up forem 

### ISSUE THREAD

**Issue by nishantwrp** [forem/forem#11558]
Got the following error while trying to setup forem.

```
== Installing dependencies ==
The Gemfile's dependencies are satisfied
Successfully installed foreman-0.87.2
Parsing documentation for foreman-0.87.2
Done installing documentation for foreman after 0 seconds
1 gem installed
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.46s.

== Copying sample files ==

== Preparing Test Elasticsearch ==
rails aborted!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [chat_channel_memberships_test/K8gHXidDT0yJK_npo9bvaA] already exists","index_uuid":"K8gHXidDT0yJK_npo9bvaA","index":"chat_channel_memberships_test"}],"type":"resource_already_exists_exception","reason":"index [chat_channel_memberships_test/K8gHXidDT0yJK_npo9bvaA] already exists","index_uuid":"K8gHXidDT0yJK_npo9bvaA","index":"chat_channel_memberships_test"},"status":400}
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/client.rb:176:in `perform_request'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.42.0/lib/ddtrace/contrib/elasticsearch/patcher.rb:106:in `block in perform_request'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.42.0/lib/ddtrace/tracer.rb:282:in `trace'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.42.0/lib/ddtrace/contrib/elasticsearch/patcher.rb:68:in `perform_request'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.9.0/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.9.0/lib/elasticsearch/api/actions/indices/create.rb:48:in `create'
/home/nishantwrp/Desktop/dev/open-source/forem/app/services/search/base.rb:41:in `create_index'
/home/nishantwrp/Desktop/dev/open-source/forem/app/services/search/cluster.rb:33:in `block in create_indexes'
/home/nishantwrp/Desktop/dev/open-source/forem/app/services/search/cluster.rb:30:in `each'
/home/nishantwrp/Desktop/dev/open-source/forem/app/services/search/cluster.rb:30:in `create_indexes'
/home/nishantwrp/Desktop/dev/open-source/forem/app/services/search/cluster.rb:19:in `setup_indexes'
/home/nishantwrp/Desktop/dev/open-source/forem/lib/tasks/search.rake:4:in `block (2 levels) in <main>'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/client.rb:70:in `start_span'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/nishantwrp/Desktop/dev/open-source/forem/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => search:setup
```

**Comment by nishantwrp** [comment]
Also, I've tried removing all the indexes from elasticsearch and running the setup command again. Still I'm getting this error.

**Comment by citizen428** [comment]
@nishantwrp I was wonderin if we wat to combine #11556 and this issue as Docker usage doesn't seem to be the deciding factor here.

**Comment by nishantwrp** [comment]
Oh, yup you're right didn't notice that.

**Comment by nishantwrp** [comment]
Hi @citizen428, Just wanted to give an update that I restarted my system and tried to run forem again both with and without docker and this is no longer an issue. So, you can close this issue if you want.

But there's another issue now :sweat:. Getting the following screen when trying to sign in.
![Screenshot_20201123_172253](https://user-images.githubusercontent.com/36989112/99959911-e2a72c00-2db1-11eb-896b-0e5187f34c5f.png)

Any ideas?

**Comment by nishantwrp** [comment]
Closing this because the original issue is resolved.
