### ISSUE TITLE
Issue in installation with docker

### ISSUE THREAD

**Issue by nishantwrp** [forem/forem#11556]
Here are the logs

```
rails_1          | 2020-11-22 16:35:41 +0000: [Faraday::TimeoutError] Operation timed out after 30002 milliseconds with 0 bytes received {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
rails_1          | 2020-11-22 16:35:41 +0000: [Faraday::TimeoutError] Attempt 1 connecting to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
rails_1          | 2020-11-22 16:35:41 +0000: PUT http://elasticsearch:9200/feed_content_development [status:400, request:30.021s, query:N/A]
rails_1          | 2020-11-22 16:35:41 +0000: > {"settings":{"index":{"number_of_shards":1,"number_of_replicas":0}}}
rails_1          | 2020-11-22 16:35:41 +0000: < {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [feed_content_development/NsgN6sQ4QEa8tEOpJb5tKQ] already exists","index_uuid":"NsgN6sQ4QEa8tEOpJb5tKQ","index":"feed_content_development"}],"type":"resource_already_exists_exception","reason":"index [feed_content_development/NsgN6sQ4QEa8tEOpJb5tKQ] already exists","index_uuid":"NsgN6sQ4QEa8tEOpJb5tKQ","index":"feed_content_development"},"status":400}
rails_1          | 2020-11-22 16:35:41 +0000: [400] {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [feed_content_development/NsgN6sQ4QEa8tEOpJb5tKQ] already exists","index_uuid":"NsgN6sQ4QEa8tEOpJb5tKQ","index":"feed_content_development"}],"type":"resource_already_exists_exception","reason":"index [feed_content_development/NsgN6sQ4QEa8tEOpJb5tKQ] already exists","index_uuid":"NsgN6sQ4QEa8tEOpJb5tKQ","index":"feed_content_development"},"status":400}
rails_1          | rake aborted!
rails_1          | Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [feed_content_development/NsgN6sQ4QEa8tEOpJb5tKQ] already exists","index_uuid":"NsgN6sQ4QEa8tEOpJb5tKQ","index":"feed_content_development"}],"type":"resource_already_exists_exception","reason":"index [feed_content_development/NsgN6sQ4QEa8tEOpJb5tKQ] already exists","index_uuid":"NsgN6sQ4QEa8tEOpJb5tKQ","index":"feed_content_development"},"status":400}
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.9.0/lib/elasticsearch/transport/client.rb:176:in `perform_request'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.42.0/lib/ddtrace/contrib/elasticsearch/patcher.rb:106:in `block in perform_request'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.42.0/lib/ddtrace/tracer.rb:282:in `trace'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.42.0/lib/ddtrace/contrib/elasticsearch/patcher.rb:68:in `perform_request'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.9.0/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.9.0/lib/elasticsearch/api/actions/indices/create.rb:48:in `create'
rails_1          | /opt/apps/forem/app/services/search/base.rb:41:in `create_index'
rails_1          | /opt/apps/forem/app/services/search/cluster.rb:33:in `block in create_indexes'
rails_1          | /opt/apps/forem/app/services/search/cluster.rb:30:in `each'
rails_1          | /opt/apps/forem/app/services/search/cluster.rb:30:in `create_indexes'
rails_1          | /opt/apps/forem/app/services/search/cluster.rb:19:in `setup_indexes'
rails_1          | /opt/apps/forem/lib/tasks/search.rake:4:in `block (2 levels) in <main>'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/client.rb:70:in `start_span'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
rails_1          | /opt/apps/forem/lib/tasks/app_initializer.rake:5:in `block (2 levels) in <main>'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/client.rb:70:in `start_span'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
rails_1          | /usr/local/bin/bundle:23:in `load'
rails_1          | /usr/local/bin/bundle:23:in `<main>'
rails_1          | Tasks: TOP => app_initializer:setup
rails_1          | (See full trace by running task with --trace)
rails_1          | 2020/11/22 16:35:41 Command exited with error: exit status 1

```

**Comment by nishantwrp** [comment]
Closing this issue in favor of #11558 as docker doesn't seem to be the problem here.
