### ISSUE TITLE
Error in app_initializer:setup run by docker compose up

### ISSUE THREAD

**Issue by ryy** [forem/forem#12068]
**Describe the bug**
 An error occurred while starting up the application with `bin/container-setup`.

**To Reproduce**

```
forem % bin/container-setup 
```

**Additional context**

```
rails_1          | Running rake app_initializer:setup...
rails_1          | rake aborted!
rails_1          | NameError: uninitialized constant RubyVM::DebugInspector
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/binding_of_caller-1.0.0/lib/binding_of_caller/mri.rb:21:in `callers'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/better_errors-2.9.1/lib/better_errors/exception_extension.rb:7:in `set_backtrace'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/cache.rb:92:in `raise'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/cache.rb:92:in `find'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
rails_1          | /opt/apps/forem/config/application.rb:18:in `<top (required)>'
rails_1          | /opt/apps/forem/rakefile:4:in `require'
rails_1          | /opt/apps/forem/rakefile:4:in `<top (required)>'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
rails_1          | /usr/local/bin/bundle:23:in `load'
rails_1          | /usr/local/bin/bundle:23:in `<main>'
rails_1          | 
rails_1          | Caused by:
rails_1          | NameError: uninitialized constant RubyVM::DebugInspector
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/binding_of_caller-1.0.0/lib/binding_of_caller/mri.rb:21:in `callers'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/better_errors-2.9.1/lib/better_errors/exception_extension.rb:7:in `set_backtrace'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/cache.rb:92:in `raise'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/cache.rb:92:in `find'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
rails_1          | /opt/apps/forem/config/application.rb:18:in `<top (required)>'
rails_1          | /opt/apps/forem/rakefile:4:in `require'
rails_1          | /opt/apps/forem/rakefile:4:in `<top (required)>'
rails_1          | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
rails_1          | /usr/share/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
rails_1          | /usr/local/bin/bundle:23:in `load'
rails_1          | /usr/local/bin/bundle:23:in `<main>'
rails_1          | (See full trace by running task with --trace)
rails_1          | 2020/12/29 21:25:19 Command exited with error: exit status 1
```

**Comment by mjobrien** [comment]
I am seeing this error as well. It appears to be connected to the version bump of the `binding_of_caller` gem in #12059.

If I limit the version of the `debug_inspector` gem on which `binding_of_caller` depends to the version from before the upgrade, `bin/container-setup` will run correctly. 

Here's the line I added to the Gemfile to override [the upgrade of `debug_inspector`](https://github.com/forem/forem/pull/12059/commits/68d6923e1747884898dd75a3243b8ccfff58858e#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL208-R208).

```rb
gem "debug_inspector", "~> 0.0.3"
```

I've not yet tracked down why the upgrade causes breakage, but I plan to look at it a bit more to see if I can sort it out.

**Comment by mjobrien** [comment]
I didn't get as far as I hoped in tracking down why the upgrade of `debug_inspector` is causing issues here.

I was able to find that [`debug_inspector` rescues `LoadError` silently](https://github.com/banister/debug_inspector/blob/7bb09517282a41b3fdf3c204f46acebf17896b51/lib/debug_inspector.rb#L7). This shows up as an error when loading `binding_of_caller` during `rake app_initializer:setup` (as shown in the initial report output).

If I comment out the `rescue LoadError` line in the gem code (`vendor/bundle/ruby/2.7.0/gems/debug_inspector-1.0.0/lib/debug_inspector.rb`), the error happens in the loading of `debug_inspector`.

```
LoadError: cannot load such file -- /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/debug_inspector-1.0.0/lib/debug_inspector.so
```

When I look for that `.so` file in the docker container, it's found under the `ext/` directory but not `lib/`.

```
$ docker-compose run bundle find /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ -name debug_inspector.so
Running command:
find /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ -name debug_inspector.so
/opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/debug_inspector-0.0.3/ext/debug_inspector/debug_inspector.so
/opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/debug_inspector-1.0.0/ext/debug_inspector/debug_inspector.so
```

I don't know enough about docker/bundler/etc. to tell if this is likely an issue specific to the forem setup or a potential bug in `debug_inspector`.

**Comment by cmgorton** [comment]
@forem/backend any thoughts on this error?

**Comment by citizen428** [comment]
@rhymes Any issue with keeping `binding_of_caller` locked at 0.8.0 for now or would you rather promote the dependency to the `Gemfile` proper? As this is a dev-dependency I'm leaning towards the former.

**Comment by rhymes** [comment]
@citizen428 sending a PR to revert that change :) no problem at all

**Comment by rhymes** [comment]
@citizen428 BTW 0.8 won't work on Ruby 3, but there's a lot of stuff that breaks with Ruby 3 now :D https://github.com/banister/binding_of_caller/releases/tag/v1.0.0

(I wonder: do we actually need that gem?)

**Comment by citizen428** [comment]
@rhymes I have a Ruby 3 tracking PR up, I'll add it to the list there :)

> (I wonder: do we actually need that gem?)

I'd say no. It's a gem that's primarily intended to be used for debugging, but I can't remember ever reaching for it, though it would have been useful at times.

**Comment by rhymes** [comment]
+1 on my side, we can ask if anyone is using it internally
