### ISSUE TITLE
Docker: ActionController::InvalidAuthenticityToken while login

### ISSUE THREAD

**Issue by f2k2game** [forem/forem#12188]
I have used ubuntu 18 and sucessfully installed forem using docker in vps.

When i to try to login using default admin password, i can't login into it.

It error shows:

```
ActionController::InvalidAuthenticityToken in Devise::SessionsController#create
ActionController::InvalidAuthenticityToken

Extracted source (around line #13):
 env["rack.session.options"][:domain] = ".#{SiteConfig.app_domain}"
    end
    @app.call(env)
  end
end

Rails.root: /opt/apps/forem

Application Trace | Framework Trace | Full Trace
app/middlewares/set_cookie_domain.rb:13:in `call'
Request
Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"dAOmDbmXWdI3Hwsx3kHg/estPl36LbDnJiera0L1dzvvgY4vUI1EgHXdbzvBkXrHvyr2u1bSo7VdSLsuLlUDlg==",
 "user"=>{"email"=>"admin@forem.local", "password"=>"[FILTERED]", "remember_me"=>"1"},
 "commit"=>"Continue"}
```

and in backend cli it shows:

```
2021-01-09T08:19:25.337Z pid=12 tid=8k28 class=Articles::ScoreCalcWorker jid=0317c64970cb9e1791ef74a8 INFO: start
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Could not resolve host: elasticsearch {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Attempt 1 connecting to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Could not resolve host: elasticsearch {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Attempt 2 connecting to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Could not resolve host: elasticsearch {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Attempt 3 connecting to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Could not resolve host: elasticsearch {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Attempt 4 connecting to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Could not resolve host: elasticsearch {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Attempt 5 connecting to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Could not resolve host: elasticsearch {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Attempt 6 connecting to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"}
sidekiq_1        | 2021-01-09 08:19:25 +0000: [Faraday::ConnectionFailed] Cannot connect to {:scheme=>"http", :user=>nil, :password=><REDACTED>, :host=>"elasticsearch", :path=>"", :port=>9200, :protocol=>"http"} after 6 tries
sidekiq_1        | 2021-01-09T08:19:25.417Z pid=12 tid=8k28 class=Articles::ScoreCalcWorker jid=0317c64970cb9e1791ef74a8 elapsed=0.079 INFO: fail
sidekiq_1        | 2021-01-09T08:19:25.418Z pid=12 tid=8k28 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"medium_priority","lock":"until_executing","class":"Articles::ScoreCalcWorker","args":[17],"jid":"0317c64970cb9e1791ef74a8","created_at":1610180000.1230652,"lock_timeout":0,"lock_expiration":null,"unique_prefix":"uniquejobs","unique_args":[17],"unique_digest":"uniquejobs:483468690538de0fc283e771a9ea277e","enqueued_at":1610180365.3319025,"error_message":"Could not resolve host: elasticsearch","error_class":"Faraday::ConnectionFailed","failed_at":1610180005.9721174,"retry_count":3,"retried_at":1610180150.9053245},"jobstr":"{\"retry\":true,\"queue\":\"medium_priority\",\"lock\":\"until_executing\",\"class\":\"Articles::ScoreCalcWorker\",\"args\":[17],\"jid\":\"0317c64970cb9e1791ef74a8\",\"created_at\":1610180000.1230652,\"lock_timeout\":0,\"lock_expiration\":null,\"unique_prefix\":\"uniquejobs\",\"unique_args\":[17],\"unique_digest\":\"uniquejobs:483468690538de0fc283e771a9ea277e\",\"enqueued_at\":1610180365.3319025,\"error_message\":\"Could not resolve host: elasticsearch\",\"error_class\":\"Faraday::ConnectionFailed\",\"failed_at\":1610180005.9721174,\"retry_count\":3,\"retried_at\":1610180150.9053245}"}
sidekiq_1        | 2021-01-09T08:19:25.418Z pid=12 tid=8k28 WARN: Faraday::ConnectionFailed: Could not resolve host: elasticsearch
sidekiq_1        | 2021-01-09T08:19:25.419Z pid=12 tid=8k28 WARN: /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/patron-0.13.3/lib/patron/session.rb:330:in `handle_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/patron-0.13.3/lib/patron/session.rb:330:in `request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter/patron.rb:32:in `block in call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter/patron.rb:29:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/faraday.rb:29:in `block in call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/client.rb:70:in `start_span'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/integrations/faraday.rb:16:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.0/lib/elasticsearch/transport/client.rb:176:in `perform_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.44.0/lib/ddtrace/contrib/elasticsearch/patcher.rb:106:in `block in perform_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.44.0/lib/ddtrace/tracer.rb:284:in `trace'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.44.0/lib/ddtrace/contrib/elasticsearch/patcher.rb:68:in `perform_request'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.10.0/lib/elasticsearch/api/actions/index.rb:74:in `index'
sidekiq_1        | /opt/apps/forem/app/services/search/client.rb:12:in `public_send'
sidekiq_1        | /opt/apps/forem/app/services/search/client.rb:12:in `block (2 levels) in method_missing'
sidekiq_1        | /opt/apps/forem/app/services/search/client.rb:36:in `request'
sidekiq_1        | /opt/apps/forem/app/services/search/client.rb:11:in `block in method_missing'
sidekiq_1        | /opt/apps/forem/app/services/search/base.rb:5:in `index'
sidekiq_1        | /opt/apps/forem/app/models/concerns/searchable.rb:11:in `index_to_elasticsearch_inline'
sidekiq_1        | /opt/apps/forem/app/workers/articles/score_calc_worker.rb:12:in `perform'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:196:in `execute_job'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
sidekiq_1        | /opt/apps/forem/lib/sidekiq/honeycomb_middleware.rb:16:in `block in call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeycomb-beeline-2.3.0/lib/honeycomb/client.rb:70:in `start_span'
sidekiq_1        | /usr/share/ruby/forwardable.rb:235:in `start_span'
sidekiq_1        | /opt/apps/forem/lib/sidekiq/honeycomb_middleware.rb:8:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.44.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:45:in `block in call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.44.0/lib/ddtrace/tracer.rb:284:in `trace'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/ddtrace-0.44.0/lib/ddtrace/contrib/sidekiq/server_tracer.rb:23:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-6.0.25/lib/sidekiq_unique_jobs/server/middleware.rb:34:in `block (2 levels) in call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-6.0.25/lib/sidekiq_unique_jobs/lock/until_executing.rb:15:in `execute'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-6.0.25/lib/sidekiq_unique_jobs/server/middleware.rb:33:in `block in call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-6.0.25/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:41:in `block in with_context'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:10:in `with'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-6.0.25/lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:41:in `with_context'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-6.0.25/lib/sidekiq_unique_jobs/server/middleware.rb:32:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/honeybadger-4.7.2/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:163:in `block in process'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:111:in `local'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:14:in `block in call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:72:in `block in wrap'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/reloader.rb:71:in `wrap'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:13:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:257:in `stats'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:13:in `call'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:78:in `global'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:10:in `with'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:33:in `prepare'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:123:in `dispatch'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:162:in `process'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:78:in `process_one'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:68:in `run'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:15:in `watchdog'
sidekiq_1        | /opt/apps/forem/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by f2k2game** [comment]
@forem/oss

**Comment by watzak** [comment]
JFYI: Have the same issue ...

**Comment by reezanahamed** [comment]
Are you working in local machine or VPS? 
If you are working in VPS, you should change APP_DOMAIN value as your IP value in ".env" file. This might solve your problem.

**Comment by watzak** [comment]
Hello @reezanahamed 
I am working locally with docker-compose! Just copied the .env_sample to .env! Didn't change anything there. Took the default values.
I am able to get the startpage, but I am not able to signin. Also registering of superadmin didn't work. Always got the error as mentioned above.
Thanx for your help. Appreciate that.

**Comment by piclez** [comment]
I'm getting the same error above. Docker on Mac.

**Comment by watzak** [comment]
@piclez Try to include `127.0.0.1 localhost rails` into your /etc/host and then enter http://rails:3000 in your browser! Then I was able to login and so on ... With http://localhost:3000 it doesn't work!
Cheers

**Comment by cmgorton** [comment]
Thanks for the follow up here @watzak !
@ piclwez and @f2k2game let me know if the suggestion from @watzak helps solve this issue. If not I will ping some people on our team to look at it. 
Thanks.

**Comment by piclez** [comment]
@cmgorton @watzak that solved my issue, thank you!

**Comment by f2k2game** [comment]
@cmgorton, I am using vps so @reezanahamed solution solved my problem, thank you!
