### ISSUE TITLE
ActionView::Template::Error (undefined method `protocol' for nil:NilClass)

### ISSUE THREAD

**Issue by aug2uag** [forem/forem#12618]
**Describe the bug**

First time launch on OSX 10.15.7 with docker-compose fails. Timeouts were extended because of timeout errors while preparing db. Trace pasted below.

**To Reproduce**

run `bin/container-setup` in OSX running Docker Desktop 3.1.0(51484) (Engine: 20.10.2, Compose: 1.27.4), extend timeout in docker-compose.yml as necessary (2700s increased 2x, retries extended 3x)

**Issue**

```bash
forem_rails      | => Booting Puma
forem_rails      | => Rails 6.0.3.4 application starting in development 
forem_rails      | => Run `rails server --help` for more startup options
forem_rails      | I, [2021-02-09T06:13:58.397652 #14]  INFO -- : Allowing 172.21.0.1 for BetterErrors and Web Console
forem_rails      | [14] Puma starting in cluster mode...
forem_rails      | [14] * Puma version: 5.2.1 (ruby 2.7.2-p137) ("Fettisdagsbulle")
forem_rails      | [14] *  Min threads: 5
forem_rails      | [14] *  Max threads: 5
forem_rails      | [14] *  Environment: development
forem_rails      | [14] *   Master PID: 14
forem_rails      | [14] *      Workers: 2
forem_rails      | [14] *     Restarts: (✔) hot (✖) phased
forem_rails      | [14] * Preloading application
forem_rails      | [14] * Listening on http://0.0.0.0:3000
forem_rails      | [14] Use Ctrl-C to stop
forem_rails      | [14] ! Promoting existing objects to old generation...
forem_rails      | [14] ! Compacting...
forem_rails      | [14] ! Friendly fork preparation complete.
forem_rails      | [14] - Worker 0 (PID: 83) booted, phase: 0
forem_rails      | [14] - Worker 1 (PID: 87) booted, phase: 0
forem_rails      | Started GET "/" for 172.21.0.10 at 2021-02-09 06:14:55 +0000
forem_rails      | Started GET "/" for 172.21.0.9 at 2021-02-09 06:14:55 +0000
forem_rails      | Cannot render console from 172.21.0.10! Allowed networks: 172.21.0.1, 127.0.0.0/127.255.255.255, ::1
forem_rails      | Cannot render console from 172.21.0.9! Allowed networks: 172.21.0.1, 127.0.0.0/127.255.255.255, ::1
forem_rails      |   ProfileField Load (4.9ms)  SELECT "profile_fields".* FROM "profile_fields" ORDER BY "profile_fields"."id" ASC LIMIT $1  [["LIMIT", 1000]]
forem_rails      |   ↳ app/models/profile.rb:30:in `refresh_attributes!'
forem_rails      |   ProfileField Load (2.0ms)  SELECT "profile_fields".* FROM "profile_fields" ORDER BY "profile_fields"."id" ASC LIMIT $1  [["LIMIT", 1000]]
forem_rails      |   ↳ app/models/profile.rb:30:in `refresh_attributes!'
forem_rails      | Unset ENV variable: APP_PROTOCOL.
forem_rails      |   User Exists? (10.9ms)  SELECT 1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
forem_rails      |   ↳ app/models/site_config.rb:25:in `<class:SiteConfig>'
forem_rails      | Unset ENV variable: TWITTER_KEY.
forem_rails      | Unset ENV variable: TWITTER_SECRET.
forem_rails      | Unset ENV variable: GITHUB_KEY.
forem_rails      | Unset ENV variable: GITHUB_SECRET.
forem_rails      | Unset ENV variable: COMMUNITY_NAME.
forem_rails      | Unset ENV variable: COMMUNITY_COPYRIGHT_START_YEAR.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: GA_TRACKING_ID.
forem_rails      | Unset ENV variable: RECAPTCHA_SITE.
forem_rails      | Unset ENV variable: RECAPTCHA_SECRET.
forem_rails      | Unset ENV variable: STRIPE_SECRET_KEY.
forem_rails      | Unset ENV variable: STRIPE_PUBLISHABLE_KEY.
forem_rails      | Unset ENV variable: MAILCHIMP_API_KEY.
forem_rails      |   SiteConfig Load (1.5ms)  SELECT var, value FROM "site_configs"
forem_rails      |   ↳ app/lib/url.rb:11:in `domain'
forem_rails      | Unset ENV variable: APP_PROTOCOL.
forem_rails      |   User Exists? (8.1ms)  SELECT 1 AS one FROM "users" LIMIT $1  [["LIMIT", 1]]
forem_rails      |   ↳ app/models/site_config.rb:25:in `<class:SiteConfig>'
forem_rails      | Unset ENV variable: TWITTER_KEY.
forem_rails      | Unset ENV variable: TWITTER_SECRET.
forem_rails      | Unset ENV variable: GITHUB_KEY.
forem_rails      | Unset ENV variable: GITHUB_SECRET.
forem_rails      | Unset ENV variable: COMMUNITY_NAME.
forem_rails      | Unset ENV variable: COMMUNITY_COPYRIGHT_START_YEAR.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: DEFAULT_EMAIL.
forem_rails      | Unset ENV variable: GA_TRACKING_ID.
forem_rails      | Unset ENV variable: RECAPTCHA_SITE.
forem_rails      | Unset ENV variable: RECAPTCHA_SECRET.
forem_rails      | Unset ENV variable: STRIPE_SECRET_KEY.
forem_rails      | Unset ENV variable: STRIPE_PUBLISHABLE_KEY.
forem_rails      | Unset ENV variable: MAILCHIMP_API_KEY.
forem_rails      |   SiteConfig Load (4.9ms)  SELECT var, value FROM "site_configs"
forem_rails      |   ↳ app/lib/url.rb:11:in `domain'
forem_rails      | Unset ENV variable: HONEYBADGER_API_KEY.
forem_rails      | Unset ENV variable: RELEASE_FOOTPRINT.
forem_rails      | Unset ENV variable: HONEYBADGER_API_KEY.
forem_rails      | Unset ENV variable: RELEASE_FOOTPRINT.
forem_rails      |    (3.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
forem_rails      |    (16.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
forem_rails      | Processing by StoriesController#index as HTML
forem_rails      |   Parameters: {"locale"=>nil}
forem_rails      | Processing by StoriesController#index as HTML
forem_rails      |   Parameters: {"locale"=>nil}
forem_rails      |   Rendering devise/registrations/new.html.erb within layouts/application
forem_rails      |   Rendering devise/registrations/new.html.erb within layouts/application
forem_rails      |   Flipper::Adapters::ActiveRecord::Gate Load (5.1ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "creator_onboarding"]]
forem_rails      |   ↳ app/services/feature_flag.rb:3:in `enabled?'
forem_rails      |   Flipper::Adapters::ActiveRecord::Gate Load (0.8ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "creator_onboarding"]]
forem_rails      |   ↳ app/services/feature_flag.rb:3:in `enabled?'
forem_rails      |   CACHE Flipper::Adapters::ActiveRecord::Gate Load (0.3ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "creator_onboarding"]]
forem_rails      |   ↳ app/services/feature_flag.rb:3:in `enabled?'
forem_rails      |   CACHE Flipper::Adapters::ActiveRecord::Gate Load (0.3ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "creator_onboarding"]]
forem_rails      |   ↳ app/services/feature_flag.rb:3:in `enabled?'
forem_rails      |   CACHE Flipper::Adapters::ActiveRecord::Gate Load (0.1ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "creator_onboarding"]]
forem_rails      |   CACHE Flipper::Adapters::ActiveRecord::Gate Load (0.1ms)  SELECT "flipper_gates".* FROM "flipper_gates" WHERE "flipper_gates"."feature_key" = $1  [["feature_key", "creator_onboarding"]]
forem_rails      |   ↳ app/services/feature_flag.rb:3:in `enabled?'
forem_rails      |   ↳ app/services/feature_flag.rb:3:in `enabled?'
forem_rails      |   Rendered shared/authentication/_email_registration_form.html.erb (Duration: 4274.1ms | Allocations: 278495)
forem_rails      |   Rendered shared/authentication/_email_registration_form.html.erb (Duration: 4207.8ms | Allocations: 278490)
forem_rails      |   Rendered shared/authentication/_initial_account_wizard.html.erb (Duration: 4295.7ms | Allocations: 278985)
forem_rails      |   Rendered shared/authentication/_initial_account_wizard.html.erb (Duration: 4235.2ms | Allocations: 278980)
forem_rails      |   Rendered devise/registrations/new.html.erb within layouts/application (Duration: 4437.3ms | Allocations: 281831)
forem_rails      |   Rendered devise/registrations/new.html.erb within layouts/application (Duration: 4449.9ms | Allocations: 281826)
forem_rails      |   Rendered layouts/_styles.html.erb (Duration: 15245.8ms | Allocations: 159419)
forem_rails      |   Rendered layouts/_styles.html.erb (Duration: 15251.2ms | Allocations: 159419)
forem_rails      | [Webpacker] Everything's up-to-date. Nothing to do
forem_rails      | [Webpacker] Everything's up-to-date. Nothing to do
forem_rails      | [Webpacker] Everything's up-to-date. Nothing to do
forem_rails      | [Webpacker] Everything's up-to-date. Nothing to do
forem_rails      | Unset ENV variable: APP_PROTOCOL.
forem_rails      |   Rendered shell/_top.html.erb (Duration: 29189.0ms | Allocations: 200006)
forem_rails      | Completed 500 Internal Server Error in 34046ms (ActiveRecord: 37.3ms | Allocations: 485775)
forem_rails      | 
forem_rails      | 
forem_rails      |   
forem_rails      | ActionView::Template::Error (undefined method `protocol' for nil:NilClass):
forem_rails      |     27:       <% end %>
forem_rails      |     28:       <%= yield(:page_meta) %>
forem_rails      |     29:       <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
forem_rails      |     30:       <%= favicon_link_tag Images::Optimizer.call(SiteConfig.favicon_url, width: 32) %>
forem_rails      |     31:       <link rel="apple-touch-icon" href="<%= optimized_image_url(SiteConfig.logo_png, width: 180, fetch_format: "png") %>">
forem_rails      |     32:       <link rel="apple-touch-icon" sizes="152x152" href="<%= optimized_image_url(SiteConfig.logo_png, width: 152, fetch_format: "png") %>">
forem_rails      |     33:       <link rel="apple-touch-icon" sizes="180x180" href="<%= optimized_image_url(SiteConfig.logo_png, width: 180, fetch_format: "png") %>">
forem_rails      |   
forem_rails      | app/lib/url.rb:69:in `local_image'
forem_rails      | app/models/site_config.rb:112:in `block in <class:SiteConfig>'
forem_rails      | app/views/shell/_top.html.erb:30
forem_rails      | app/views/layouts/application.html.erb:1
forem_rails      | app/controllers/application_controller.rb:50:in `verify_private_forem'
forem_rails      | app/middlewares/set_cookie_domain.rb:13:in `call'
forem_rails      | Unset ENV variable: APP_PROTOCOL.
forem_rails      |   Rendered shell/_top.html.erb (Duration: 29268.0ms | Allocations: 200007)
forem_rails      | Completed 500 Internal Server Error in 34092ms (ActiveRecord: 52.0ms | Allocations: 485771)
forem_rails      | 
forem_rails      | 
forem_rails      |   
forem_rails      | ActionView::Template::Error (undefined method `protocol' for nil:NilClass):
forem_rails      |     27:       <% end %>
forem_rails      |     28:       <%= yield(:page_meta) %>
forem_rails      |     29:       <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
forem_rails      |     30:       <%= favicon_link_tag Images::Optimizer.call(SiteConfig.favicon_url, width: 32) %>
forem_rails      |     31:       <link rel="apple-touch-icon" href="<%= optimized_image_url(SiteConfig.logo_png, width: 180, fetch_format: "png") %>">
forem_rails      |     32:       <link rel="apple-touch-icon" sizes="152x152" href="<%= optimized_image_url(SiteConfig.logo_png, width: 152, fetch_format: "png") %>">
forem_rails      |     33:       <link rel="apple-touch-icon" sizes="180x180" href="<%= optimized_image_url(SiteConfig.logo_png, width: 180, fetch_format: "png") %>">
forem_rails      |   
forem_rails      | app/lib/url.rb:69:in `local_image'
forem_rails      | app/models/site_config.rb:112:in `block in <class:SiteConfig>'
forem_rails      | app/views/shell/_top.html.erb:30
forem_rails      | app/views/layouts/application.html.erb:1
forem_rails      | app/controllers/application_controller.rb:50:in `verify_private_forem'
forem_rails      | app/middlewares/set_cookie_domain.rb:13:in `call'
forem_rails      | ** [Honeybadger] Unable to send error report: API key is missing. id=01741dcc-b876-4c24-aa05-d2d8484c1fca level=3 pid=83
forem_sidekiq    | 2021/02/09 06:15:49 Received 500 from http://rails:3000. Sleeping 1m0s
forem_rails      | ** [Honeybadger] Unable to send error report: API key is missing. id=be3c6155-e93a-4428-9b56-ea7cf816720f level=3 pid=87
forem_seed       | 2021/02/09 06:15:49 Received 500 from http://rails:3000. Sleeping 1m0s
forem_rails      | Started GET "/" for 172.21.0.9 at 2021-02-09 06:16:49 +0000
forem_rails      | Started GET "/" for 172.21.0.10 at 2021-02-09 06:16:49 +0000
forem_rails      | Cannot render console from 172.21.0.9! Allowed networks: 172.21.0.1, 127.0.0.0/127.255.255.255, ::1
forem_rails      | Cannot render console from 172.21.0.10! Allowed networks: 172.21.0.1, 127.0.0.0/127.255.255.255, ::1
```

**Comment by aug2uag** [comment]
missing .env in instructions, closing
