### ISSUE TITLE
Flaky tests for data update scripts on ProfileField 

### ISSUE THREAD

**Issue by djuber** [forem/forem#13030]
**Describe the bug**

Depending on the spec execution order, the expectations for DataUpdateScripts::SetProperDisplayAreaForProfileFields and  DataUpdateScripts::FixProfileFieldEdgeCases can fail.

**To Reproduce**

Fairly horrible copy/paste from the knapsack generated execution in the failing container ( https://travis-ci.com/github/forem/forem/jobs/491785877#L1000-L1012 ) - I was able to reproduce this locally but have not bisected it to determine which minimal ordering is needed to reproduce. 

```
 bundle exec rspec --format progress  --default-path spec "spec/services/notifications/new_comment/send_spec.rb" "spec/system/search/display_articles_search_spec.rb" "spec/policies/comment_policy_spec.rb" "spec/services/moderator/banish_user_spec.rb" "spec/requests/articles/video_player_show_spec.rb" "spec/workers/metrics/record_daily_usage_worker_spec.rb" "spec/requests/tag_adjustments_spec.rb" "spec/system/tags/user_updates_a_tag_spec.rb" "spec/requests/user/user_organization_spec.rb" "spec/system/admin/admin_manages_profile_fields_spec.rb" "spec/system/user_logs_in_with_password_spec.rb" "spec/system/authentication/redirects_using_referer_spec.rb" "spec/models/user_subscription_spec.rb" "spec/system/articles/user_deletes_an_article_spec.rb" "spec/system/admin/admin_awards_badges_spec.rb" "spec/workers/moderator/banish_user_worker_spec.rb" "spec/services/search/chat_channel_membership_spec.rb" "spec/system/admin/admin_manages_configuration_spec.rb" "spec/services/profiles/update_spec.rb" "spec/system/user/user_settings_response_templates_spec.rb" "spec/services/markdown_processor/fixer/base_spec.rb" "spec/helpers/articles_helper_spec.rb" "spec/workers/metrics/record_daily_notifications_worker_spec.rb" "spec/services/article_with_video_creation_service_spec.rb" "spec/services/edge_cache/bust_podcast_episode_spec.rb" "spec/workers/notifications/new_badge_achievement_worker_spec.rb" "spec/decorators/listing_decorator_spec.rb" "spec/lib/acts_as_taggable_on/tag_parser_spec.rb" "spec/services/audit/notification_spec.rb" "spec/liquid_tags/codepen_tag_spec.rb" "spec/models/profile_field_group_spec.rb" "spec/workers/tags/bust_cache_worker_spec.rb" "spec/liquid_tags/jsitor_tag_spec.rb" "spec/liquid_tags/gist_tag_spec.rb" "spec/serializers/search/podcast_episode_serializer_spec.rb" "spec/lib/data_update_scripts/backfill_usernames_spec.rb" "spec/models/concerns/purgeable_spec.rb" "spec/workers/feeds/import_articles_worker_spec.rb" "spec/workers/organizations/bust_cache_worker_spec.rb" "spec/services/github/oauth_client_spec.rb" "spec/liquid_tags/codesandbox_tag_spec.rb" "spec/helpers/organization_helper_spec.rb" "spec/system/banned_user_interactions_spec.rb" "spec/mailers/digest_mailer_spec.rb" "spec/mailers/verification_mailer_spec.rb" "spec/workers/chat_channels/indexes_memberships_worker_spec.rb" "spec/helpers/listing_helper_spec.rb" "spec/liquid_tags/wikipedia_tag_spec.rb" "spec/services/twitter_client/client_spec.rb" "spec/services/search/query_builders/chat_channel_membership_spec.rb" "spec/routing/i18n_routes_spec.rb" "spec/services/images/optimizer_spec.rb" "spec/system/articles/user_visits_articles_by_timeframe_spec.rb" "spec/models/comment_spec.rb" "spec/requests/stories_index_spec.rb" "spec/requests/admin/users_manage_spec.rb" "spec/system/notifications/notifications_page_spec.rb" "spec/models/notification_spec.rb" "spec/system/user_uses_the_editor_spec.rb" "spec/services/broadcasts/welcome_notification/generator_spec.rb" "spec/liquid_tags/user_subscription_tag_spec.rb" "spec/system/dashboards/user_scrolls_down_dashboard_follows_spec.rb" "spec/services/slack/messengers/comment_user_warned_spec.rb" "spec/requests/podcasts/podcast_show_spec.rb" "spec/requests/html_variant_successes_spec.rb" "spec/services/articles/attributes_spec.rb" "spec/services/webhook/payload_adapter_spec.rb" "spec/services/badges/award_yearly_club_spec.rb" "spec/requests/api_secrets_destroy_spec.rb" "spec/requests/admin/badges_spec.rb" "spec/lib/data_update_scripts/cleanup_articles_with_invalid_feed_source_url_spec.rb" "spec/services/search/tag_spec.rb" "spec/requests/html_variant_trials_spec.rb" "spec/system/admin/admin_manages_organizations_spec.rb" "spec/system/collections/user_views_collection_articles_spec.rb" "spec/requests/admin/welcome_spec.rb" "spec/requests/admin/permissions_spec.rb" "spec/services/edge_cache/bust_article_spec.rb" "spec/requests/admin/tools_spec.rb" "spec/requests/profiles_request_spec.rb" "spec/models/site_config_spec.rb" "spec/services/payments/customer_spec.rb" "spec/requests/invitations_spec.rb" "spec/workers/comments/calculate_score_worker_spec.rb" "spec/policies/internal_policy_spec.rb" "spec/lib/data_update_scripts/update_article_main_image_path_spec.rb" "spec/policies/github_repo_policy_spec.rb" "spec/models/broadcast_spec.rb" "spec/requests/notification_counts_spec.rb" "spec/workers/users/resave_articles_worker_spec.rb" "spec/decorators/sponsorship_decorator_spec.rb" "spec/services/bufferizer/listings_tweet_spec.rb" "spec/workers/search/index_worker_spec.rb" "spec/lib/data_update_scripts/index_chat_channel_memberships_to_elasticsearch_spec.rb" "spec/system/user/user_edits_customization_spec.rb" "spec/views/users/settings_spec.rb" "spec/models/profile_spec.rb" "spec/models/html_variant_spec.rb" "spec/models/podcast_episode_spec.rb" "spec/requests/admin/tags/moderators_spec.rb" "spec/models/response_template_spec.rb" "spec/requests/followings_spec.rb" "spec/liquid_tags/comment_tag_spec.rb" "spec/system/admin/admin_deletes_user_spec.rb" "spec/services/exporter/articles_spec.rb" "spec/uploaders/profile_image_uploader_spec.rb" "spec/requests/admin/navigation_link_spec.rb" "spec/models/listing_spec.rb" "spec/requests/sitemaps_spec.rb" "spec/requests/api/v0/followers_spec.rb" "spec/requests/admin/users/gdpr_delete_requests_spec.rb" "spec/workers/notifications/moderation_notification_worker_spec.rb" "spec/services/moderator/delete_user_spec.rb" "spec/requests/admin/chat_channel_spec.rb" "spec/lib/data_update_scripts/add_single_resource_role_to_tech_admins_spec.rb" "spec/services/markdown_processor/parser_spec.rb" "spec/requests/collections_spec.rb" "spec/system/dashboards/user_followers_display_spec.rb" "spec/services/notifications/new_badge_achievement/send_spec.rb" "spec/services/suggester/users/sidebar_spec.rb" "spec/services/user_subscriptions/is_subscribed_cache_checker_spec.rb" "spec/lib/data_update_scripts/update_articles_cached_entities_spec.rb" "spec/workers/comments/create_first_reaction_worker_spec.rb" "spec/workers/reactions/bust_homepage_cache_worker_spec.rb" "spec/workers/reactions/bust_reactable_cache_worker_spec.rb" "spec/requests/video_states_update_spec.rb" "spec/models/display_ad_spec.rb" "spec/serializers/search/comment_serializer_spec.rb" "spec/lib/data_update_scripts/cleanup_orphan_git_hub_repositories_spec.rb" "spec/services/html/parser_spec.rb" "spec/services/webhook/dispatch_event_spec.rb" "spec/requests/api_secrets_create_spec.rb" "spec/liquid_tags/listing_tag_spec.rb" "spec/services/edge_cache/bust_comment_spec.rb" "spec/policies/follow_policy_spec.rb" "spec/models/listing_category_spec.rb" "spec/decorators/organization_decorator_spec.rb" "spec/services/tag_moderators/remove_spec.rb" "spec/models/navigation_link_spec.rb" "spec/requests/async_info_spec.rb" "spec/services/profile_fields/import_from_csv_spec.rb" "spec/services/edge_cache/bust_organization_spec.rb" "spec/system/admin/admin_creates_new_page_spec.rb" "spec/lib/app_secrets_spec.rb" "spec/routing/all_routes_spec.rb" "spec/requests/sidebars_spec.rb" "spec/tasks/fastly_spec.rb" "spec/system/feedback_message_spec.rb" "spec/models/ahoy/visit_spec.rb" "spec/views/layouts/signup_modal.html.erb_spec.rb" "spec/liquid_tags/podcast_tag_spec.rb" "spec/policies/api_secret_policy_spec.rb" "spec/requests/user/user_profile_spec.rb" "spec/system/authentication/user_logs_in_with_apple_spec.rb" "spec/mailers/notify_mailer_spec.rb" "spec/services/analytics_service_spec.rb" "spec/requests/articles/articles_spec.rb" "spec/requests/comments_create_spec.rb" "spec/services/search/feed_content_spec.rb" "spec/system/homepage/user_visits_homepage_articles_spec.rb" "spec/system/dashboards/user_sorts_dashboard_articles_spec.rb" "spec/system/homepage/user_visits_homepage_with_announcement_spec.rb" "spec/workers/users/record_field_test_event_worker_spec.rb" "spec/system/homepage/user_visits_homepage_spec.rb" "spec/system/user_views_a_reading_list_spec.rb" "spec/system/authentication/user_logs_in_with_email_spec.rb" "spec/requests/api/v0/organizations_spec.rb" "spec/decorators/user_decorator_spec.rb" "spec/models/profile_pin_spec.rb" "spec/services/bulk_sql_delete_spec.rb" "spec/workers/follows/update_points_worker_spec.rb" "spec/requests/admin/html_variants_spec.rb" "spec/requests/admin/privileged_reactions_spec.rb" "spec/requests/api/v0/videos_spec.rb" "spec/system/podcasts/user_visits_podcast_page_spec.rb" "spec/requests/admin/badge_achievements_spec.rb" "spec/services/badges/award_tag_spec.rb" "spec/liquid_tags/link_tag_spec.rb" "spec/services/notifications/notifiable_action/send_spec.rb" "spec/services/tag_adjustment_creation_service_spec.rb" "spec/workers/reactions/update_relevant_scores_worker_spec.rb" "spec/workers/rating_votes/assign_rating_worker_spec.rb" "spec/services/notifications/milestone/send_spec.rb" "spec/system/link_for_tags_in_posts_in_notifications_spec.rb" "spec/services/articles/creator_spec.rb" "spec/requests/api/v0/admin/configs_spec.rb" "spec/services/notifications/moderation/send_spec.rb" "spec/requests/admin/listings_categories_spec.rb" "spec/lib/acts_as_taggable_on/tag_spec.rb" "spec/workers/listings/expire_old_listings_worker_spec.rb" "spec/services/edge_cache/bust_commentable_spec.rb" "spec/services/badges/award_fab_five_spec.rb" "spec/workers/notifications/welcome_notification_worker_spec.rb" "spec/services/authentication/providers_spec.rb" "spec/models/users/suspended_username_spec.rb" "spec/lib/data_update_scripts/populate_explicit_follow_points_spec.rb" "spec/policies/organization_policy_spec.rb" "spec/lib/data_update_scripts/set_onboarding_profile_fields_for_existing_forems_spec.rb" "spec/helpers/social_link_helper_spec.rb" "spec/requests/follows_bulk_update_spec.rb" "spec/models/email_authorization_spec.rb" "spec/services/edge_cache/bust_spec.rb" "spec/workers/mentions/send_email_notification_worker_spec.rb" "spec/workers/broadcasts/send_welcome_notifications_worker_spec.rb" "spec/requests/email_subscriptions_spec.rb" "spec/system/authentication/beta_access_providers_spec.rb" "spec/services/images/generate_social_image_spec.rb" "spec/policies/article_policy_spec.rb" "spec/system/admin/admin_updates_tag_spec.rb" "spec/services/credits/buyer_spec.rb" "spec/decorators/comment_decorator_spec.rb" "spec/requests/admin/secrets_spec.rb" "spec/models/article_destroy_spec.rb" "spec/services/articles/destroyer_spec.rb" "spec/system/authentication/user_with_suspended_username_spec.rb" "spec/requests/liquid_embeds_spec.rb" "spec/services/chat_channels/create_with_users_spec.rb" "spec/requests/admin/overview_spec.rb" "spec/models/podcast_episode_appearance_spec.rb" "spec/requests/admin/nested_sidebar_spec.rb" "spec/system/admin/admin_creates_new_event_spec.rb" "spec/models/credit_spec.rb" "spec/requests/display_ad_events_spec.rb" "spec/requests/follows_show_spec.rb" "spec/services/bufferizer/main_tweet_spec.rb" "spec/policies/chat_channel_membership_policy_spec.rb" "spec/liquid_tags/twitch_tag_spec.rb" "spec/services/color/accessibility_spec.rb" "spec/policies/tag_policy_spec.rb" "spec/services/profile_fields/field_definition_spec.rb" "spec/lib/data_update_scripts/remove_feeds_import_feature_flag_spec.rb" "spec/liquid_tags/dotnet_fiddle_tag_spec.rb" "spec/workers/comments/send_email_notification_worker_spec.rb" "spec/workers/metrics/check_data_update_script_statuses_spec.rb" "spec/models/forem_instance_spec.rb" "spec/models/timeframe_spec.rb" "spec/views/stories/sign_in_invitation.html.erb_spec.rb" "spec/workers/badge_achievements/badge_award_worker_spec.rb" "spec/policies/stripe_active_card_policy_spec.rb" "spec/workers/articles/bust_cache_worker_spec.rb" "spec/initializers/application_config_spec.rb" "spec/workers/listings/bust_cache_worker_spec.rb" "spec/liquid_tags/kotlin_tag_spec.rb" "spec/models/html_variant_success_spec.rb" "spec/models/html_variant_trial_spec.rb" "spec/workers/badge_achievements/send_email_notification_worker_spec.rb" "spec/liquid_tags/next_tech_tag_spec.rb" "spec/lib/data_update_scripts/append_collective_noun_to_community_name_spec.rb" "spec/workers/slack/messengers/worker_spec.rb" "spec/requests/open_search_spec.rb" "spec/services/markdown_processor/fixer/fix_for_comment_spec.rb" "spec/lib/reverse_markdown/converters/custom_pre_spec.rb" "spec/liquid_tags/reddit_tag_spec.rb" "spec/services/medium_article_retrieval_service_spec.rb" "spec/services/markdown_processor/fixer/fix_all_spec.rb" "spec/policies/admin_policy_spec.rb" "spec/lib/release_phase_notifier_spec.rb" "spec/models/banished_user_spec.rb" "spec/services/users/safe_remote_profile_image_url_spec.rb" "spec/liquid_tags/stackery_tag_spec.rb" "spec/policies/video_policy_spec.rb" "spec/models/audit_log_spec.rb" "spec/liquid_tags/asciinema_tag_spec.rb" "spec/policies/buffer_update_policy_spec.rb" "spec/liquid_tags/soundcloud_tag_spec.rb" "spec/workers/notifications/milestone_worker_spec.rb" "spec/lib/throttled_call_spec.rb" "spec/liquid_tags/git_pitch_tag_spec.rb" "spec/workers/notifications/update_worker_spec.rb" "spec/services/re_captcha/check_registration_enabled_spec.rb" "spec/services/markdown_processor/fixer/fix_for_preview_spec.rb" "spec/requests/pusher_auth_spec.rb" "spec/services/images/profile_spec.rb" "spec/workers/notifications/tag_adjustment_notification_worker_spec.rb" "spec/routing/devices_routes_spec.rb" "spec/routing/profile_admin_routes_spec.rb" "spec/liquid_tags/instagram_tag_spec.rb" "spec/services/slack/messengers/potential_spammer_spec.rb" "spec/workers/pages/bust_cache_worker_spec.rb" "spec/lib/liquid/raw_spec.rb" "spec/services/edge_cache/bust_tag_spec.rb" "spec/workers/podcast_episodes/create_worker_spec.rb" "spec/helpers/feedback_messages_helper_spec.rb" "spec/liquid_tags/parler_tag_spec.rb" "spec/workers/metrics/record_background_queue_stats_worker_spec.rb" "spec/services/slack/messengers/note_spec.rb" "spec/services/loggers/log_worker_queue_stats_spec.rb" "spec/lib/data_update_scripts/set_proper_display_area_for_profile_fields_spec.rb" "spec/liquid_tags/twitter_timeline_tag_spec.rb" "spec/workers/events/bust_cache_worker_spec.rb" "spec/liquid_tags/replit_tag_spec.rb" "spec/workers/emails/enqueue_digest_worker_spec.rb" "spec/lib/data_update_scripts/update_user_update_rate_limit_default_spec.rb" "spec/lib/data_update_scripts/update_default_email_addresses_spec.rb" "spec/workers/credits/sync_counter_cache_spec.rb" "spec/liquid_tags/blogcast_tag_spec.rb" "spec/liquid_tags/speakerdeck_tag_spec.rb" "spec/workers/notifications/remove_old_notifications_worker_spec.rb" "spec/workers/notifications/new_follower_worker_spec.rb" "spec/helpers/date_helper_spec.rb" "spec/models/email_message_spec.rb" "spec/workers/notifications/remove_all_worker_spec.rb" "spec/services/slack/announcer_spec.rb" "spec/workers/bust_cache_path_worker_spec.rb" "spec/services/data_sync/elasticsearch/base_spec.rb" "spec/lib/data_update_scripts/fix_profile_field_edge_cases_spec.rb" "spec/services/secrets/generator_spec.rb" "spec/liquid_tags/runkit_tag_spec.rb" "spec/liquid_tags/details_tag_spec.rb" "spec/services/markdown_processor/traverser_spec.rb" "spec/views/email_subscriptions/unsubscribe.html.erb_spec.rb" "spec/services/edge_cache/bust_sidebar_spec.rb" "spec/lib/data_update_scripts/remove_collective_noun_from_site_config_spec.rb" "spec/services/badges/award_sixteen_week_streak_spec.rb" "spec/lib/liquid/echo_spec.rb" "spec/helpers/rate_limit_checker_helper_spec.rb" "spec/workers/podcasts/bust_cache_worker_spec.rb" "spec/refinements/string_to_boolean_spec.rb" "spec/services/edge_cache/bust_podcast_spec.rb" "spec/services/edge_cache/bust_events_spec.rb" "spec/helpers/notifications_helper_spec.rb" "spec/services/data_sync/elasticsearch/organization_spec.rb" "spec/initializers/carrierwave_monkeypatch_spec.rb" "spec/services/badges/award_four_week_streak_spec.rb" "spec/lib/sidekiq/worker_retries_exhausted_reporter_spec.rb" "spec/liquid_tags/slideshare_tag_spec.rb" "spec/services/edge_cache/bust_page_spec.rb" "spec/services/feeds/clean_html_spec.rb" "spec/lib/reverse_markdown/converters/custom_text_spec.rb" "spec/services/data_sync/elasticsearch/article_spec.rb" "spec/services/users/profile_image_generator_spec.rb" "spec/services/audit/subscribe_spec.rb" "spec/services/badges/award_eight_week_streak_spec.rb" "spec/lib/liquid/render_spec.rb" "spec/liquid_tags/null_tag_spec.rb" "spec/lib/liquid/variable_spec.rb" "spec/services/data_sync/elasticsearch/tag_spec.rb" "spec/services/audit/helper_spec.rb" "spec/services/data_sync/elasticsearch/user_spec.rb" "spec/models/shared_examples/user_subscription_sourceable_spec.rb" "spec/models/podcast_ownership_spec.rb" "spec/services/credits/manage_spec.rb" "spec/models/webhook/event_spec.rb" "spec/workers/mentions/create_all_worker_spec.rb" "spec/services/podcasts/get_episode_spec.rb" "spec/workers/users/follow_worker_spec.rb" "spec/policies/chat_channel_policy_spec.rb" "spec/uploaders/badge_uploader_spec.rb" "spec/liquid_tags/github_tag/github_readme_tag_spec.rb" "spec/workers/follows/create_chat_channel_worker_spec.rb" "spec/view_objects/cloud_cover_url_spec.rb" "spec/workers/organizations/update_organization_articles_paths_worker_spec.rb" "spec/models/github_issue_spec.rb" "spec/services/tag_moderators/add_trusted_role_spec.rb" "spec/models/custom_profile_field_spec.rb" "spec/services/podcasts/feed_spec.rb" "spec/requests/api/v0/analytics_spec.rb" "spec/requests/registrations_spec.rb" "spec/requests/admin/users_spec.rb" "spec/system/articles/user_visits_articles_by_tag_spec.rb" "spec/requests/moderations_spec.rb" "spec/system/comments/user_edits_a_comment_spec.rb" "spec/requests/chat_channels_spec.rb" "spec/requests/reactions_spec.rb" "spec/system/articles/user_fixes_a_draft_spec.rb" "spec/system/user/user_edits_extensions_spec.rb" "spec/system/user/user_self_destroy_spec.rb" "spec/requests/articles/articles_update_spec.rb" "spec/requests/chat_channel_memberships_spec.rb" "spec/services/search/base_spec.rb" "spec/system/podcasts/user_visits_podcasts_root_page_spec.rb" "spec/requests/stripe_active_cards_spec.rb" "spec/system/collections/user_views_collections_spec.rb" "spec/requests/admin/display_ads_spec.rb" "spec/models/collection_spec.rb" "spec/models/buffer_update_spec.rb" "spec/requests/buffer_updates_spec.rb" "spec/services/exporter/comments_spec.rb" "spec/requests/organizations_update_spec.rb" "spec/services/notifications/update_spec.rb" "spec/services/exporter/service_spec.rb" "spec/system/admin/admin_manages_reports_spec.rb" "spec/services/articles/feeds/basic_spec.rb" "spec/models/identity_spec.rb" "spec/system/organization/user_leaves_an_organization_spec.rb" "spec/requests/admin/broadcasts_spec.rb" "spec/models/poll_vote_spec.rb" "spec/models/notification_subscription_spec.rb" "spec/requests/comments_destroy_spec.rb" "spec/initializers/rack/attack_spec.rb" "spec/requests/article_approvals_spec.rb" "spec/models/message_spec.rb" "spec/system/search/user_searches_users_spec.rb" "spec/services/moderator/manage_activity_and_roles_spec.rb"



Failures:

  1) DataUpdateScripts::SetProperDisplayAreaForProfileFields migrates profile fields to proper areas
     Failure/Error:
       expect(ProfileField.find_by(attribute_name: "instagram_url").display_area)
         .to eq("settings_only")
     
     NoMethodError:
       undefined method `display_area' for nil:NilClass
     # ./spec/lib/data_update_scripts/set_proper_display_area_for_profile_fields_spec.rb:10:in `block (2 levels) in <main>'
     # ./spec/rails_helper.rb:151:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:151:in `block (2 levels) in <top (required)>'

  2) DataUpdateScripts::FixProfileFieldEdgeCases migrates profile fields to proper areas
     Failure/Error:
       expect(ProfileField.find_by(attribute_name: "git_lab_url").display_area)
         .to eq("settings_only")
     
     NoMethodError:
       undefined method `display_area' for nil:NilClass
     # ./spec/lib/data_update_scripts/fix_profile_field_edge_cases_spec.rb:10:in `block (2 levels) in <main>'
     # ./spec/rails_helper.rb:151:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:151:in `block (2 levels) in <top (required)>'

Finished in 9 minutes 26 seconds (files took 5.46 seconds to load)
2692 examples, 2 failures, 4 pending

```

Bisection gets me down to this reproduction case (I'm removing the second failing test since I expect it's the same root cause):

```
~/src/forem$ rspec ./spec/system/dashboards/user_sorts_dashboard_articles_spec.rb ./spec/lib/data_update_scripts/fix_profile_field_edge_cases_spec.rb

[Zonebie] Setting timezone: ZONEBIE_TZ="Adelaide"
......F

Failures:

  1) DataUpdateScripts::FixProfileFieldEdgeCases migrates profile fields to proper areas
     Failure/Error:
       expect(ProfileField.find_by(attribute_name: "git_lab_url").display_area)
         .to eq("settings_only")
     
     NoMethodError:
       undefined method `display_area' for nil:NilClass
     # ./spec/lib/data_update_scripts/fix_profile_field_edge_cases_spec.rb:10:in `block (2 levels) in <main>'
     # ./spec/rails_helper.rb:151:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:151:in `block (2 levels) in <top (required)>'

Finished in 24.23 seconds (files took 4.1 seconds to load)
7 examples, 1 failure

Failed examples:

rspec ./spec/lib/data_update_scripts/fix_profile_field_edge_cases_spec.rb:7 # DataUpdateScripts::FixProfileFieldEdgeCases migrates profile fields to proper areas
```

**Expected behavior**

All tests pass.

**Additional context**

This seems rare - there is probably one spec file removing profile fields and it has to run in the container with the data updates, and run before the data updates specs do, in order to cause an issue.

**Comment by djuber** [comment]
Seems like this was added in https://github.com/forem/forem/pull/8865 to work around a failing rss reader test (that needed to create a db / table during setup?) - I'd like to try setting this test to transactional again and find out if the truncation was really the right solution or if travis had other issues and this got clumped together with the rss reader spec (now missing).
