### ISSUE TITLE
Fix Flaky viewArticleDiscussion.spec.js Test 

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#14478]
The `viewArticleDiscussion.spec.js` has been skipped using `.skip` on the particular test, `follows and unfollows a user from a comment preview card`, that has been failing. In order to prevent future flakiness while ensuring that our code is covered by tests, we need to fix this spec.

Below is the most recent failure due to flakiness:
```
    1) follows and unfollows a user from a comment preview card
    ✓ initializes the follow button when a new comment is added (2381ms)
  1 passing (30s)
  1 failing
  1) View article discussion
       follows and unfollows a user from a comment preview card:
     CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is not visible:
`<button name="button" type="button" data-info="{&quot;id&quot;:1,&quot;className&quot;:&quot;User&quot;,&quot;style&quot;:&quot;&quot;}" class="crayons-btn follow-action-button whitespace-nowrap w-100 follow-user showing" data-fetched="fetched" data-verb="unfollow">Follow</button>`
This element `<button.crayons-btn.follow-action-button.whitespace-nowrap.w-100.follow-user.showing>` is not visible because its parent `<div#comment-profile-preview-content-1.profile-preview-card__content.crayons-dropdown.showing>` has CSS property: `display: none`
Fix this problem, or use `{force: true}` to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
      at $Cy.ensureVisibility (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:148405:24)
      at runAllChecks (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:136083:14)
      at retryActionability (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:136137:16)
      at tryCatcher (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:13212:23)
      at Function.Promise.attempt.Promise.try (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:10486:29)
      at tryFn (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:153198:21)
      at whenStable (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:153236:12)
      at http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:152728:16
      at tryCatcher (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:13212:23)
      at Promise._settlePromiseFromHandler (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:11147:31)
      at Promise._settlePromise (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:11204:18)
      at Promise._settlePromise0 (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:11249:10)
      at Promise._settlePromises (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:11329:18)
      at Promise._fulfill (http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:11273:18)
      at http://127.0.0.1:35505/__cypress/runner/cypress_runner.js:12887:46
  From Your Spec Code:
      at Context.eval (http://127.0.0.1:35505/__cypress/tests?p=cypress/integration/seededFlows/articleFlows/viewArticleDiscussion.spec.js:121:35)
```

The PR that skipped this specific test is PR #14477

**Comment by djuber** [comment]
It seems like https://github.com/forem/forem/pull/14473 may be related (this was the commit where we started to see this happen, and directly impacts the positioning or visibility of the preview card as well as modifying some event listeners around scroll, possibly tied to an insta-click preview load).

Testing locally I can recreate this intermittently - effectively the profile preview is shown, then changes to hidden/not shown, either immediately (before the follow button is pushed) or after the first follow (before the "following" button is pushed to unfollow). 

This doesn't happen consistently, but it's more often than not.

My first hunch was that the request for the preview was surrounding (initiated before, completed after) the follow button press, and that this preview load completion was the event clearing the shown dropdown.

My second hunch was that there are hover rules in css, as well as click event listeners in js, that might reveal the dropdown.
