### ISSUE TITLE
SMTP is not working

### ISSUE THREAD

**Issue by f2k2game** [forem/forem#17540]
I have successfully installed forem selfhost.  Problem is I can't receive any email notification, i tried to reset password but i didn't receive any email to reset password.

So i tried to config SMTP, I have tried Sendinblue, SparkPost, Zoho SMTP and also even tried Google SMTP but none of them works, i tried to change every port and tested and also i have tested with https://www.gmass.co/smtp-test which works fine but not in forem.

I have read SMTP related article in forem but everyone suggesting sendgrid, but i can't able to create account in sendgrid. 

I tried testing using python using gmail SMTP details
```
import smtplib

gmail_user = 'you@gmail.com'
gmail_password = 'P@ssword!'

sent_from = gmail_user
to = ['me@gmail.com', 'bill@gmail.com']
subject = 'OMG Super Important Message'
body = 'Hey, whats up?\n\n- You'

email_text = """\
From: %s
To: %s
Subject: %s

%s
""" % (sent_from, ", ".join(to), subject, body)

try:
    server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
    server.ehlo()
    server.login(gmail_user, gmail_password)
    server.sendmail(sent_from, to, email_text)
    server.close()

    print(Email sent!)
except:
    print(Something went wrong...)
```

It is also works good in python but not working in forem.

**Comment by maestromac** [comment]
Moved this to forem/forem as this is not a self-host issue.

@f2k2game can you please navigate to `your-selfhost.com/admin/sidekiq/morgue` and tell me if you see any SMTP related failures?

**Comment by f2k2game** [comment]
No, It doesn't work, I even tried it using ruby script which works completely fine

```
require 'net/smtp'

FROM_EMAIL = "support@domain.com"
PASSWORD = "password"
TO_EMAIL = "f2k2@gmail.com"

smtp = Net::SMTP.new 'smtp.gmail.com', 587
smtp.enable_starttls

message = <<END_OF_MESSAGE
From: MyDomain <support@domain.com>
To: ToName <f2k2@gmail.com>
Subject: Mail From Ruby 

Hello there!!
This is a message from Ruby.
END_OF_MESSAGE

smtp.start('received-from-goes-here', FROM_EMAIL, PASSWORD, :plain)
smtp.send_message(message, FROM_EMAIL, TO_EMAIL)

smtp.finish()
```

I tried same options in forem SMTP
```
User name: support@domain.com
Password: password
Address: smtp.gmail.com
Authentication: plain
Domain: (i tried blank field and domian.com)
Port: 587
From email address: support@domain.com
Reply to email address: contact@domain.com
```

but it doesn't work in forem.

**Comment by maestromac** [comment]
@f2k2game your username should be your SMTP Gmail. can you please navigate to the morgue and see if there's a new error.

**Comment by f2k2game** [comment]
@maestromac  No, there is no new error.

<img width="1280" alt="Screenshot 2022-05-04 at 9 15 58 AM" src="https://user-images.githubusercontent.com/45148319/166620325-227fc028-2010-479d-bbb0-83878fe60ae8.png">

**Comment by reezan-ahamed** [comment]
you can see error log while run `journalctl -f -u forem-rails.service`

**Comment by f2k2game** [comment]
```
forem-rails[126471]: I, [2022-05-12T09:52:58.697849 #7]  INFO -- : [cbf68ceb-7473-43ed-b8b6-f6fa86befbc5] Started GET "/users/password/new?i=i" for 106.197.175.54 at 2022-05-12 09:52:58 +0000
forem-rails[126471]: I, [2022-05-12T09:52:58.707884 #7]  INFO -- : [cbf68ceb-7473-43ed-b8b6-f6fa86befbc5] Processing by PasswordsController#new as */*
forem-rails[126471]: I, [2022-05-12T09:52:58.708194 #7]  INFO -- : [cbf68ceb-7473-43ed-b8b6-f6fa86befbc5]   Parameters: {"i"=>"i"}
forem-rails[126471]: I, [2022-05-12T09:52:58.718718 #7]  INFO -- : [cbf68ceb-7473-43ed-b8b6-f6fa86befbc5]   Rendered devise/passwords/new.html.erb within layouts/application (Duration: 2.6ms | Allocations: 673)
forem-rails[126471]: I, [2022-05-12T09:52:58.720896 #7]  INFO -- : [cbf68ceb-7473-43ed-b8b6-f6fa86befbc5]   Rendered layout layouts/application.html.erb (Duration: 4.8ms | Allocations: 827)
forem-rails[126471]: I, [2022-05-12T09:52:58.722077 #7]  INFO -- : [cbf68ceb-7473-43ed-b8b6-f6fa86befbc5] Completed 200 OK in 13ms (Views: 6.2ms | ActiveRecord: 0.0ms | Allocations: 1974)
forem-rails[126471]: I, [2022-05-12T09:52:59.489724 #9]  INFO -- : [e3b79fd5-8c57-432f-924c-fb4ce0ad2624] Started GET "/async_info/base_data" for 106.197.175.54 at 2022-05-12 09:52:59 +0000
forem-rails[126471]: I, [2022-05-12T09:52:59.501967 #9]  INFO -- : [e3b79fd5-8c57-432f-924c-fb4ce0ad2624] Processing by AsyncInfoController#base_data as JSON
forem-rails[126471]: I, [2022-05-12T09:52:59.502683 #9]  INFO -- : [e3b79fd5-8c57-432f-924c-fb4ce0ad2624]   Parameters: {"locale"=>nil}
forem-rails[126471]: I, [2022-05-12T09:52:59.512502 #9]  INFO -- : [e3b79fd5-8c57-432f-924c-fb4ce0ad2624] Completed 200 OK in 9ms (Views: 0.3ms | ActiveRecord: 0.8ms | Allocations: 1354)
forem-rails[126471]: I, [2022-05-12T09:53:02.685493 #9]  INFO -- : [a331f0a4-da64-42f8-9eb2-aec565dd2f1c] Started POST "/users/password" for 106.197.175.54 at 2022-05-12 09:53:02 +0000
forem-rails[126471]: I, [2022-05-12T09:53:02.733998 #9]  INFO -- : [a331f0a4-da64-42f8-9eb2-aec565dd2f1c] Processing by PasswordsController#create as HTML
forem-rails[126471]: I, [2022-05-12T09:53:02.734648 #9]  INFO -- : [a331f0a4-da64-42f8-9eb2-aec565dd2f1c]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"[FILTERED]"}, "commit"=>"Send me reset password instructions"}
forem-rails[126471]: DEPRECATION WARNING: default_worker_options is deprecated and will be removed from Sidekiq 7.0 (use default_job_options instead) (called from bust_cache at /opt/apps/forem/app/models/user.rb:618)
forem-rails[126471]: DEPRECATION WARNING: default_worker_options is deprecated and will be removed from Sidekiq 7.0 (use default_job_options instead) (called from bust_cache at /opt/apps/forem/app/models/user.rb:618)
forem-rails[126471]: DEPRECATION WARNING: default_worker_options is deprecated and will be removed from Sidekiq 7.0 (use default_job_options instead) (called from bust_cache at /opt/apps/forem/app/models/user.rb:618)
forem-rails[126471]: I, [2022-05-12T09:53:02.827828 #9]  INFO -- : [a331f0a4-da64-42f8-9eb2-aec565dd2f1c] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: e1fae1e6-5456-4b96-8888-36435f3af576) to Async(mailers) with arguments: "DeviseMailer", "reset_password_instructions", "deliver_now", {:args=>[#<GlobalID:0x00007f6c475f8740 @uri=#<URI::GID gid://practical-developer/User/8>>, "EnRgUJWEnuZexmEgS2Z9", {}]}
forem-rails[126471]: I, [2022-05-12T09:53:02.836106 #9]  INFO -- : [a331f0a4-da64-42f8-9eb2-aec565dd2f1c] Redirected to https://www.domain.com/enter
forem-rails[126471]: I, [2022-05-12T09:53:02.838623 #9]  INFO -- : [a331f0a4-da64-42f8-9eb2-aec565dd2f1c] Completed 302 Found in 102ms (ActiveRecord: 13.4ms | Allocations: 7381)
forem-rails[126471]: I, [2022-05-12T09:53:02.909593 #9]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [e1fae1e6-5456-4b96-8888-36435f3af576] Performing ActionMailer::MailDeliveryJob (Job ID: e1fae1e6-5456-4b96-8888-36435f3af576) from Async(mailers) enqueued at 2022-05-12T09:53:02Z with arguments: "DeviseMailer", "reset_password_instructions", "deliver_now", {:args=>[#<GlobalID:0x00007f6c476e31c8 @uri=#<URI::GID gid://practical-developer/User/8>>, "EnRgUJWEnuZexmEgS2Z9", {}]}
forem-rails[126471]: I, [2022-05-12T09:53:02.916743 #9]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [e1fae1e6-5456-4b96-8888-36435f3af576]   Rendered devise/mailer/reset_password_instructions.html.erb (Duration: 1.3ms | Allocations: 140)
forem-rails[126471]: I, [2022-05-12T09:53:03.178601 #9]  INFO -- : [9e804766-f552-44ca-87fb-ba6c6a89a8bb] Started GET "/enter" for 106.197.175.54 at 2022-05-12 09:53:03 +0000
forem-rails[126471]: I, [2022-05-12T09:53:03.193947 #9]  INFO -- : [9e804766-f552-44ca-87fb-ba6c6a89a8bb] Processing by RegistrationsController#new as HTML
forem-rails[126471]: I, [2022-05-12T09:53:03.263408 #9]  INFO -- : [9e804766-f552-44ca-87fb-ba6c6a89a8bb]   Rendered devise/registrations/new.html.erb within layouts/application (Duration: 57.8ms | Allocations: 9198)
forem-rails[126471]: I, [2022-05-12T09:53:03.292092 #9]  INFO -- : [9e804766-f552-44ca-87fb-ba6c6a89a8bb]   Rendered layout layouts/application.html.erb (Duration: 86.6ms | Allocations: 14101)
forem-rails[126471]: I, [2022-05-12T09:53:03.308398 #9]  INFO -- : [9e804766-f552-44ca-87fb-ba6c6a89a8bb] Completed 200 OK in 113ms (Views: 99.5ms | ActiveRecord: 3.1ms | Allocations: 15333)
forem-rails[126471]: I, [2022-05-12T09:53:04.017573 #9]  INFO -- : [479a757e-e204-47c8-89f2-44d02ef56576] Started GET "/async_info/base_data" for 106.197.175.54 at 2022-05-12 09:53:04 +0000
forem-rails[126471]: I, [2022-05-12T09:53:04.031310 #9]  INFO -- : [479a757e-e204-47c8-89f2-44d02ef56576] Processing by AsyncInfoController#base_data as JSON
forem-rails[126471]: I, [2022-05-12T09:53:04.031458 #9]  INFO -- : [479a757e-e204-47c8-89f2-44d02ef56576]   Parameters: {"locale"=>nil}
forem-rails[126471]: I, [2022-05-12T09:53:04.043265 #9]  INFO -- : [479a757e-e204-47c8-89f2-44d02ef56576] Completed 200 OK in 10ms (Views: 0.6ms | ActiveRecord: 1.2ms | Allocations: 1354)
forem-rails[126471]: I, [2022-05-12T09:53:13.310568 #9]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [e1fae1e6-5456-4b96-8888-36435f3af576] Delivered mail 627cd8fee1687_95039855634@forem-pod.mail (10389.9ms)
forem-rails[126471]: E, [2022-05-12T09:53:13.311783 #9] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [e1fae1e6-5456-4b96-8888-36435f3af576] Error performing ActionMailer::MailDeliveryJob (Job ID: e1fae1e6-5456-4b96-8888-36435f3af576) from Async(mailers) in 10483.14ms: EOFError (end of file reached):
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:227:in `rbuf_fill'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:193:in `readuntil'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:203:in `readline'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:1040:in `recv_response'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:642:in `block in do_start'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:1050:in `critical'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:642:in `do_start'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:604:in `start'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/actionmailer-7.0.2.4/lib/action_mailer/base.rb:565:in `block in deliver_mail'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/notifications.rb:206:in `block in instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/notifications.rb:206:in `instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/actionmailer-7.0.2.4/lib/action_mailer/base.rb:563:in `deliver_mail'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/actionmailer-7.0.2.4/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/actionmailer-7.0.2.4/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/actionmailer-7.0.2.4/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/actionmailer-7.0.2.4/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:59:in `block in _perform_job'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/i18n-1.10.0/lib/i18n.rb:328:in `with_locale'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `instance_exec'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `instance_exec'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:58:in `_perform_job'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:20:in `_perform_job'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:46:in `perform_now'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:14:in `block in perform_now'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:25:in `block in instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/notifications.rb:206:in `block in instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/notifications.rb:206:in `instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:35:in `instrument'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:14:in `perform_now'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/logging.rb:18:in `block in perform_now'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/tagged_logging.rb:37:in `tagged'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/tagged_logging.rb:99:in `tagged'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/logging.rb:25:in `tag_logger'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/logging.rb:18:in `perform_now'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:24:in `block in execute'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/reloader.rb:72:in `block in wrap'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/reloader.rb:71:in `wrap'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `instance_exec'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:22:in `execute'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/activejob-7.0.2.4/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
forem-rails[126471]: /opt/apps/forem/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
```

This is my log file for forget password action.

**Comment by f2k2game** [comment]
It's the bug in forem. I just updated my forem in latest version sha256:3ef385ff2ec0f327942fff93c7c089254b1c9f7632859bad6853fefa1ea52e2c, now its works.
