### ISSUE TITLE
Flakey user_visits_homepage_articles_spec.rb and user_visits_podcasts_root_page_spec.rb

### ISSUE THREAD

**Issue by mstruve** [forem/forem#4888]
Related to #4884 

Specs failed when running CI against master.
```
4) User visits a homepage when more_articles meta tags contains the qualified community name in og:site_name
     Failure/Error: articles = create_list(:article, 3, reactions_count: 30, featured: true)
     0m
     ActiveRecord::QueryCanceled:
       PG::QueryCanceled: ERROR:  canceling statement due to statement timeout
       CONTEXT:  while inserting index tuple (5,17) in relation "index_tags_on_name"
       : INSERT INTO "tags" ("created_at", "name", "updated_at") VALUES ($1, $2, $3) RETURNING "id"
     
     
     
     # ./spec/system/homepage/user_visits_homepage_articles_spec.rb:58:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::QueryCanceled:
     #   ERROR:  canceling statement due to statement timeout
     #   CONTEXT:  while inserting index tuple (5,17) in relation "index_tags_on_name"
     #   ./spec/system/homepage/user_visits_homepage_articles_spec.rb:58:in `block (3 levels) in <top (required)>'
  5) User visits /pod page doesn't display an unreachable podcast
     Failure/Error: let!(:un_podcast_episode) { create(:podcast_episode, podcast: podcast, reachable: false) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: Guid has already been taken
     
     
     
     # ./spec/system/podcasts/user_visits_podcasts_root_page_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:89:in `block (2 levels) in <top (required)>'

rspec ./spec/system/homepage/user_visits_homepage_articles_spec.rb:70 # User visits a homepage when more_articles meta tags contains the qualified community name in og:site_name
rspec ./spec/system/podcasts/user_visits_podcasts_root_page_spec.rb:29 # User visits /pod page doesn't display an unreachable podcast
```

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by mstruve** [comment]
I don't believe we have seen this one since a lot of our recent Spec and CI improvements so I am closing
